# Generated by Django 3.1.6 on 2021-02-09 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ipv4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.FloatField()),
                ('geoname_id', models.TextField()),
                ('registered_country_geoname_id', models.TextField()),
                ('represented_country_geoname_id', models.TextField()),
                ('is_anonymous_proxy', models.TextField()),
                ('is_satellite_provider', models.TextField()),
                ('postal_code', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('accuracy_radius', models.TextField()),
            ],
        ),
    ]
